// nigeriaStates.ts
export const nigeriaStates: { [state: string]: string[] } = {
  "Abia": ["Aba North", "Aba South", "Umuahia", "Isiala Ngwa", "Ohafia", "Bende"],
  "Adamawa": ["Yola North", "Yola South", "Mubi", "Gombi", "Numan"],
  "Akwa Ibom": ["Uyo", "Eket", "Ikot Ekpene", "Oron", "Abak"],
  "Anambra": ["Awka North", "Awka South", "Onitsha North", "Onitsha South", "Nnewi"],
  "Bauchi": ["Bauchi", "Azare", "Misau", "Jama'are", "Katagum"],
  "Benue": ["Makurdi", "Gboko", "Otukpo", "Katsina-Ala", "Vandeikya"],
  "Borno": ["Maiduguri", "Biu", "Chibok", "Askira", "Damboa"],
  "Cross River": ["Calabar", "Ogoja", "Ikom", "Obudu", "Ugep"],
  "Delta": ["Warri", "Asaba", "Sapele", "Ughelli", "Agbor"],
  "Ebonyi": ["Abakaliki", "Afikpo", "Onicha", "Ezza", "Izzi"],
  "Edo": ["Benin City", "Ekpoma", "Auchi", "Igueben", "Uromi"],
  "Ekiti": ["Ado Ekiti", "Ikere", "Iyin", "Omuo", "Ijero"],
  "Enugu": ["Enugu North", "Enugu South", "Nsukka", "Udi", "Oji River"],
  "FCT": ["Abuja Municipal", "Gwagwalada", "Kuje", "Bwari", "Kwali"],
  "Gombe": ["Gombe", "Dukku", "Kaltungo", "Billiri", "Bajoga"],
  "Imo": ["Owerri", "Okigwe", "Orlu", "Mbaitoli", "Ngor Okpala"],
  "Jigawa": ["Dutse", "Hadejia", "Kazaure", "Gumel", "Birnin Kudu"],
  "Kaduna": ["Kaduna North", "Kaduna South", "Zaria", "Kafanchan", "Soba"],
  "Kano": ["Kano Municipal", "Fagge", "Tarauni", "Nassarawa", "Dala"],
  "Katsina": ["Katsina", "Daura", "Funtua", "Malumfashi", "Dutsin-Ma"],
  "Kebbi": ["Birnin Kebbi", "Argungu", "Zuru", "Yauri", "Bagudo"],
  "Kogi": ["Lokoja", "Okene", "Idah", "Kabba", "Ajaokuta"],
  "Kwara": ["Ilorin East", "Ilorin West", "Offa", "Omu-Aran", "Patigi"],
  "Lagos": ["Ikeja", "Surulere", "Epe", "Ikorodu", "Badagry"],
  "Nasarawa": ["Lafia", "Keffi", "Akwanga", "Nasarawa", "Toto"],
  "Niger": ["Minna", "Bida", "Suleja", "Kontagora", "New Bussa"],
  "Ogun": ["Abeokuta", "Ijebu Ode", "Sango Ota", "Sagamu", "Ifo"],
  "Ondo": ["Akure", "Ondo Town", "Owo", "Ikare", "Odigbo"],
  "Osun": ["Oshogbo", "Ife", "Ilesha", "Ikire", "Ede"],
  "Oyo": ["Ibadan North", "Ibadan South", "Ogbomoso", "Oyo East", "Oyo West"],
  "Plateau": ["Jos North", "Jos South", "Pankshin", "Barkin Ladi", "Shendam"],
  "Rivers": ["Port Harcourt", "Obio/Akpor", "Bonny", "Eleme", "Ikwerre"],
  "Sokoto": ["Sokoto North", "Sokoto South", "Tambuwal", "Gwadabawa", "Wurno"],
  "Taraba": ["Jalingo", "Bali", "Wukari", "Sardauna", "Ibi"],
  "Yobe": ["Damaturu", "Potiskum", "Gashua", "Geidam", "Nguru"],
  "Zamfara": ["Gusau", "Kaura Namoda", "Talata Mafara", "Anka", "Maradun"],
};
